version: "3"
services:
  tex:
    image: face0u0/ulatex:2021-basic-v1
    tty: true
    volumes:
      - ../b-policy:/tex
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    command: >
      bash -c "
        sudo tlmgr install float url &&
        bash
      "
