version: "3"
services:
  pluto:
    image: pluto
    tty: true
    privileged: true
    volumes:
      - "/var/run/dbus:/var/run/dbus"
      - "/var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket"
      - "$HOME/.Xauthority:/home/user/.Xauthority:ro"
      - ..:/workdir
    network_mode: "host"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - DISPLAY=$DISPLAY
